# Generated by Django 5.2.8 on 2025-11-28 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名')),
                ('description', models.TextField(max_length=200, verbose_name='对于这个分类的描述')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='创建这个标签的时间')),
            ],
            options={
                'db_table': 'blog_category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='标签的名称')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='标签创建的时间')),
            ],
            options={
                'db_table': 'blog_tag',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章名称')),
                ('content', models.TextField(max_length=3000, verbose_name='文章内容')),
                ('Cover', models.ImageField(blank=True, null=True, upload_to='', verbose_name='封面')),
                ('status', models.CharField(choices=[('private', '私密'), ('archive', '归档'), ('draft', '草稿'), ('published', '已发布')], default='draft', max_length=10, verbose_name='文章状态')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comments', models.IntegerField(default=0, verbose_name='评论数')),
                ('views', models.IntegerField(default=0, verbose_name='观看数')),
                ('create_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创作者')),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
