# Generated by Django 5.2.8 on 2025-12-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_category_article_tag_alter_article_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Cover',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('private', '私密'), ('draft', '草稿'), ('archive', '归档'), ('published', '已发布')], default='draft', max_length=10, verbose_name='文章状态'),
        ),
    ]
