# Generated by Django 5.2.8 on 2025-12-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_cover_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('archive', '归档'), ('draft', '草稿'), ('private', '私密'), ('published', '已发布')], default='draft', max_length=10, verbose_name='文章状态'),
        ),
    ]
