# Generated by Django 5.2.8 on 2025-12-05 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='上传图片')),
                ('video', models.FileField(upload_to='video/%Y/%m/%d/', verbose_name='上传视频')),
                ('title', models.CharField(max_length=100, verbose_name='名称')),
                ('description', models.TextField(max_length=100, verbose_name='描述')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '媒体',
                'verbose_name_plural': '媒体',
                'db_table': 'media',
                'ordering': ['-create_date'],
            },
        ),
    ]
